nama_saya = input("masukan nama: ")
nim_saya = input("masukan nim : ")

print("------------------------")
print(".wlcome to", nama_saya)
print(".with your nim", nim_saya)
print("------------------------")

print()
print("Question 1.")
print("diketahui sisi = 6, sebutkan nama dan hitunglah luas bangun datar tersebut!")
persegi = input("Nama bangun datar : ")
sisi1 = float (input("sisi = "))
sisi2 = float (input("sisi = "))
print("luas bangun datar tersebut adalah",persegi,"dan luas bangun datar tersebut adalah",sisi1 * sisi2)

print()
print("Question 2. ")
print("diketahui alas = 7, tinggi = 8, hitunglah luas bangun datar tersebut!")
segitiga = input("nama bangundatar :")
alas = float (input("alas ="))
tinggi = float (input("tinggi ="))
print("bangun datar tersebut adalah",segitiga,"dan luas bangun datar tersebut adalah",alas * tinggi)

print()
print("Question 3. ")
print("diketahui panjang = 4, lebar = 9, sebutkan nama dan hitunglah luas bangun datar tersebut!")
persegi_panjang = input("nama bangun datar : ")
panjang = float (input("panjang = "))
lebar = float (input("lebar = "))
print("bangun datar tersebut adalah",persegi_panjang,"dan luas bangun datar tersebut adalah",panjang * lebar)

print()
print("Question 4.")
print("diketahui jari-jari = 56, sebutkan nama dan luas bangun datar tersebut!")
lingkaran = input("nama bangun datar : ")
L = float (input("L = "))
R = float (input("R = "))
print("bangun datar tersebut adalah",lingkaran,"dan luas bangun datar tersebut adalah",L * R)

print()
print("Question 5.")
print("diketahui diagonal I = 4, diagonal II = 8, sebutkan nama dan hitunglah luas bangun datar tersebut!")
belah_ketupat = input("nama bangun datar : ")
diagonal_I = float (input("diagonal I = "))
diagonal_II = float (input("diagonal II = "))
print("bangun datar tersebut adalah",belah_ketupat,"dan luas bangun datar tersebut adalah",diagonal_I * diagonal_II)

print()
print("Question 6.")
print("diketahui sisi AB dan CD sejajar, sisi AB = 6, sisi CD = 8, tinggi = 3. sebutkan nama dan luas bangun datar tersebut!")
trapesium = input("nama bangun datar : ")
sisi_AB = float (input("sisi_AB = "))
sisi_CD = float (input("sisi_CD = "))
print("bangun datar tersebut adalah",trapesium,"dan luas bangun datar tersebut adalah",sisi_AB * sisi_CD)

print()
print("Question 7.")
print("diketahui sebuah jajar genjang dengan alas = 9, tinggi = 7. hitunglah luas bangun datar tersebut")
alas = float (input("alas = "))
tinggi = float (input("tinggi"))
print("luas jajar genjang adalah",alas * tinggi)

print()
print(".--------------------------------------.")
print(".'thank you very much for you atention'.")
print(".--------------------------------------.")
